require_relative 'kgrader/assignment'
require_relative 'kgrader/cli'
require_relative 'kgrader/course'
require_relative 'kgrader/errors'
require_relative 'kgrader/filesystem'
require_relative 'kgrader/roster'
require_relative 'kgrader/task'
require_relative 'kgrader/util'
